services:
  db:
    image: postgres:17
    container_name: postgres-demo
    environment:
      # Not as root
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      # standard path
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      # check the connection status
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: spring-app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${SERVER_PORT}:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      # validate on startup
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      # avoid showing all SQL in production
      SPRING_JPA_SHOW_SQL: false

volumes:
  # persistent
  postgres_data: