package org.iris.observability.quality.providers;

import org.junit.jupiter.api.Test;

import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Unit tests for {@link BuildInfoSectionProvider} reading the real
 * {@code META-INF/build-info.properties} generated by Spring Boot's
 * {@code build-info} Maven goal.
 *
 * <p>No fixture: the file IS on the test classpath after `mvn
 * test-compile`. Tests pin the contract that the file is generated
 * AND that the provider extracts the expected fields, doubling as a
 * detector if the build-info Maven plugin is ever silently disabled.
 */
class BuildInfoSectionProviderTest {

    private final BuildInfoSectionProvider provider = new BuildInfoSectionProvider();

    @Test
    void parse_returnsAvailableTrueWhenPropertiesPresentOnClasspath() {
        Map<String, Object> result = provider.parse();

        // Pinned: if this fails, the build-info Maven goal is no longer
        // running (someone disabled it). The /actuator/quality endpoint's
        // build section would silently regress to "available: false".
        assertThat(result).containsEntry("available", true);
    }

    @Test
    void parse_includesArtifactVersionTimeKeys() {
        Map<String, Object> result = provider.parse();

        assertThat(result)
                .containsKey("artifact")
                .containsKey("version")
                .containsKey("time")
                .containsKey("javaVersion")
                .containsKey("springBootVersion");
    }

    @Test
    void parse_artifactIsKnownProjectName() {
        // The artifact in build-info.properties matches the pom.xml
        // <artifactId>. Pinned for the dashboard which displays it as
        // the project's friendly name.
        Map<String, Object> result = provider.parse();

        assertThat(result.get("artifact")).isEqualTo("iris");
    }

    @Test
    void parse_javaVersionIsCurrentJvm() {
        // System property is read inline — value matches the JVM
        // running the tests (today: Java 25 in Phase B / Java 21 in compat).
        Map<String, Object> result = provider.parse();

        assertThat(result.get("javaVersion"))
                .isEqualTo(System.getProperty("java.version"));
    }

    @Test
    void parse_versionAndSpringBootVersionAreSameValue() {
        // Pinned historical: spring-boot version is embedded in
        // build.version (NOT a separate property). The dashboard shows
        // both fields; both must reflect the same string for consistency.
        Map<String, Object> result = provider.parse();

        assertThat(result.get("springBootVersion")).isEqualTo(result.get("version"));
    }
}
